// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AdjustClientDebt(arg1:number,arg2:number):Promise<db.Client>;

export function CreateClient(arg1:string,arg2:string,arg3:string):Promise<db.Client>;

export function CreateOrder(arg1:number,arg2:string,arg3:number,arg4:Array<Record<string, any>>):Promise<db.Order>;

export function CreateProduct(arg1:string,arg2:string,arg3:number,arg4:string):Promise<db.Product>;

export function DebugSchema():Promise<Record<string, Array<string>>>;

export function DeleteClient(arg1:number):Promise<void>;

export function DeleteOrder(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function ExportOrderPDF(arg1:number):Promise<Array<number>>;

export function GetClient(arg1:number):Promise<db.Client>;

export function GetClients(arg1:string,arg2:number,arg3:number):Promise<db.PaginatedResult_myproject_backend_db_Client_>;

export function GetDashboardMetrics(arg1:string):Promise<db.DashboardData>;

export function GetOrder(arg1:number):Promise<db.OrderDetail>;

export function GetOrderStatuses():Promise<Array<string>>;

export function GetOrders(arg1:string,arg2:number,arg3:string,arg4:number,arg5:number,arg6:string):Promise<db.PaginatedResult_myproject_backend_db_OrderDetail_>;

export function GetProduct(arg1:number):Promise<db.Product>;

export function GetProducts(arg1:string,arg2:number,arg3:number):Promise<db.PaginatedResult_myproject_backend_db_Product_>;

export function Greet(arg1:string):Promise<string>;

export function UpdateClient(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<db.Client>;

export function UpdateOrder(arg1:number,arg2:string,arg3:string,arg4:any,arg5:Array<Record<string, any>>):Promise<db.Order>;

export function UpdateProduct(arg1:number,arg2:string,arg3:string,arg4:number,arg5:string):Promise<db.Product>;
