// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateClient(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateClient'](arg1, arg2, arg3, arg4);
}

export function CreateInvoice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateInvoice'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateOrder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateOrder'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProduct(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProduct'](arg1, arg2, arg3, arg4);
}

export function DeleteOrder(arg1) {
  return window['go']['main']['App']['DeleteOrder'](arg1);
}

export function ExportInvoicePDF(arg1) {
  return window['go']['main']['App']['ExportInvoicePDF'](arg1);
}

export function ExportOrderPDF(arg1) {
  return window['go']['main']['App']['ExportOrderPDF'](arg1);
}

export function GetClient(arg1) {
  return window['go']['main']['App']['GetClient'](arg1);
}

export function GetClients(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetClients'](arg1, arg2, arg3);
}

export function GetDashboardMetrics(arg1) {
  return window['go']['main']['App']['GetDashboardMetrics'](arg1);
}

export function GetInvoice(arg1) {
  return window['go']['main']['App']['GetInvoice'](arg1);
}

export function GetInvoices(arg1, arg2) {
  return window['go']['main']['App']['GetInvoices'](arg1, arg2);
}

export function GetOrder(arg1) {
  return window['go']['main']['App']['GetOrder'](arg1);
}

export function GetOrderStatuses() {
  return window['go']['main']['App']['GetOrderStatuses']();
}

export function GetOrders(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetOrders'](arg1, arg2, arg3, arg4, arg5);
}

export function GetProduct(arg1) {
  return window['go']['main']['App']['GetProduct'](arg1);
}

export function GetProducts(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProducts'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function UpdateClient(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateClient'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateOrder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateOrder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateProduct(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProduct'](arg1, arg2, arg3, arg4, arg5);
}
